export const dict = {
  id: {
    nav: {
      about: "Tentang",
      projects: "Karya",
      skills: "Keahlian",
      experience: "Pengalaman",
      contact: "Kontak",
      hire: "Hubungi Saya",
      available: "Tersedia untuk Freelance",
    },
    hero: {
      eyebrow: "Front-End Developer · Bandung, ID",
      headline_1: "I BUILD DIGITAL",
      headline_2: "EXPERIENCES.",
      subheadline: "Spesialis Front-End dengan 3+ tahun pengalaman dalam membangun aplikasi web modern, performa tinggi, dan arsitektur scalable menggunakan Next.js, React, Angular, dan TypeScript.",
      view_work: "Lihat Karya",
      lets_talk: "Mari Berdiskusi",
      experience_badge: "3+ Tahun Pengalaman",
      role_badge: "Front-End Engineer",
      location_badge: "Bandung, Indonesia",
      status: "Tersedia untuk Freelance & Kolaborasi",
    },
    about: {
      section_label: "01 / TENTANG SAYA",
      heading: "Menggabungkan ketelitian rekayasa dengan keindahan visual.",
      bio_p1: "Saya adalah Wildan Jaelani, seorang Front-End Developer berbasis di Bandung dengan pengalaman lebih dari 3 tahun. Saya fokus membangun antarmuka web yang tidak hanya indah dipandang, tetapi juga cepat, mudah diakses, dan memiliki struktur kode yang terukur.",
      bio_p2: "Dalam keseharian, saya terbiasa bekerja dengan ekosistem modern seperti Next.js, React, Angular, TypeScript, dan arsitektur Monorepo. Saya menyukai tantangan dalam menyederhanakan masalah kompleks menjadi solusi digital yang intuitif.",
      highlights: [
        { label: "Pengalaman", value: "3+ Tahun" },
        { label: "Spesialisasi", value: "Next.js · Angular · TS" },
        { label: "Domisili", value: "Bandung, ID" },
        { label: "Status", value: "Open for Freelance" },
      ],
    },
    projects_section: {
      section_label: "02 / KARYA PILIHAN",
      heading: "Studi Kasus & Proyek",
      desc: "Eksplorasi proyek nyata dari aplikasi skala enterprise dengan arsitektur monorepo hingga platform bisnis interaktif.",
      view_demo: "Lihat Demo Langsung",
      internal_project: "Internal Enterprise Project",
      case_study: "Studi Kasus",
      tech_stack: "Teknologi",
    },
    skills_section: {
      section_label: "03 / KEAHLIAN & STACK",
      heading: "Teknologi & Instrumen",
      desc: "Fondasi teknis yang saya gunakan sehari-hari untuk menghadirkan antarmuka web berkinerja tinggi dan scalable.",
      all: "Semua",
    },
    experience_section: {
      section_label: "04 / PERJALANAN KARIR",
      heading: "Pengalaman Profesional",
      desc: "Jejak langkah kontribusi dalam membangun produk digital dan sistem front-end skala besar.",
    },
    contact_section: {
      section_label: "05 / MULAI KOLABORASI",
      heading_1: "LET'S BUILD",
      heading_2: "SOMETHING GREAT.",
      desc: "Punya ide proyek, kebutuhan front-end developer freelance, atau ingin sekadar berdiskusi seputar web development? Pintu selalu terbuka.",
      chat_whatsapp: "Chat via WhatsApp",
      send_email: "Kirim Email",
      view_linkedin: "Terhubung di LinkedIn",
      availability: "Tersedia untuk project baru",
      location_text: "Bandung, Jawa Barat, Indonesia (WIB / UTC+7)",
    },
    footer: {
      crafted: "Didesain & Dibangun oleh Wildan Jaelani",
      rights: "Hak Cipta Dilindungi.",
      local_time: "Waktu Bandung (WIB)",
      back_to_top: "Kembali ke Atas",
    },
    profile: {
      name: "Wildan Jaelani",
      role: "Front-End Developer",
      bio: "Front-End Developer dengan pengalaman 3+ tahun. Spesialis Next.js, React, Angular, dan TypeScript. Terbiasa menangani aplikasi skala enterprise dan proyek freelance.",
      email: "jwildan22904@gmail.com",
      whatsapp: "62895413466226",
      linkedin: "https://www.linkedin.com/in/wildan-j-82016b250/",
      location: "Bandung, Jawa Barat, Indonesia",
      photo: "/wildan2.png",
    },
    skills: [
      {
        category: "Frameworks",
        items: ["Next.js", "React", "Angular", "Angular Material", "Laravel"],
      },
      {
        category: "Languages",
        items: ["TypeScript", "JavaScript", "HTML5", "CSS3", "PHP"],
      },
      {
        category: "Styling & UI",
        items: ["Tailwind CSS", "Responsive UI", "Motion UI", "Bootstrap"],
      },
      {
        category: "Architecture & Tools",
        items: ["Hono (RPC)", "Monorepo", "REST API", "Git", "Axios", "Vercel"],
      },
    ],
    experiences: [
      {
        role: "Freelance Front-End Developer",
        company: "PT. Infinys System Indonesia",
        period: "Mei 2023 – Sekarang",
        type: "Freelance / Contract",
        summary: "Memimpin implementasi UI sistem event management enterprise berskala besar dengan arsitektur modern.",
        points: [
          "Membangun aplikasi event management berskala enterprise menggunakan Angular dan Angular Material.",
          "Menerapkan arsitektur Monorepo untuk modularitas kode, reusabilitas komponen, dan efisiensi tim.",
          "Melakukan integrasi backend API menggunakan Hono (RPC) dengan type-safety end-to-end.",
          "Mengembangkan modul antarmuka performa tinggi dengan TypeScript, Next.js, dan Tailwind CSS.",
        ],
      },
      {
        role: "Front-End Developer Intern",
        company: "PT. Infinys System Indonesia",
        period: "Jan 2023 – Apr 2023",
        type: "Internship",
        summary: "Berkontribusi dalam slicing halaman, konsumsi REST API, dan optimalisasi tata letak responsif.",
        points: [
          "Melakukan slicing wireframe UI/UX menjadi halaman web yang presisi dan responsif menggunakan Tailwind CSS.",
          "Mengintegrasikan dan mengonsumsi REST API pada aplikasi berbasis Next.js dan React.",
          "Memastikan aksesibilitas, performa render yang cepat, dan konsistensi lintas perangkat.",
        ],
      },
    ],
    projects: [
      {
        id: "01",
        title: "Event Management Application",
        category: "Enterprise System",
        subtitle: "Aplikasi Enterprise & Arsitektur Monorepo",
        desc: "Platform manajemen acara skala enterprise yang dirancang untuk mengelola alur pendaftaran, penjadwalan sesi, dan operasional acara secara komprehensif. Dibangun dengan Angular dan Angular Material serta arsitektur Monorepo dan integrasi Hono RPC untuk front-end yang tangguh dan modular.",
        tags: ["Angular", "TypeScript", "Hono RPC", "Monorepo", "Angular Material"],
        link: "",
        image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&q=85",
        year: "2023 – 2024",
        highlight: "Enterprise Scale",
      },
      {
        id: "02",
        title: "Nusantara Coffee",
        category: "Brand & Web Platform",
        subtitle: "Cafe Landing Page & Interactive Menu",
        desc: "Landing page modern untuk coffee shop dengan estetika hangat dan responsif. Dilengkapi dengan fitur filtering menu interaktif secara dinamis, tombol pemesanan WhatsApp instan, dan optimasi performa web berbasis Next.js dan Tailwind CSS.",
        tags: ["Next.js", "TypeScript", "Tailwind CSS", "Vercel"],
        link: "https://cafe-landing-sage.vercel.app/",
        image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=1200&q=85",
        year: "2024",
        highlight: "Live Platform",
      },
      {
        id: "03",
        title: "Golden Stall (Warung Emas)",
        category: "Hospitality & Dining",
        subtitle: "Fine Dining Restaurant Showcase",
        desc: "Antarmuka web premium untuk restoran fine dining dengan presentasi visual yang elegan. Menggabungkan kurasi fotografi hidangan beresolusi tinggi, filter kategori menu yang intuitif, serta micro-interactions yang mulus.",
        tags: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion"],
        link: "https://warung-emas.vercel.app",
        image: "https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=1200&q=85",
        year: "2024",
        highlight: "Live Platform",
      },
    ],
    game: {
      hub_title: "Game Hub",
      hub_desc: "Eksplorasi mini game interaktif yang dibangun dengan logika Front-End murni.",
      play_now: "Mainkan Sekarang",
      title: "Tech Memory Match",
      desc: "Temukan pasangan ikon teknologi di balik kartu!",
      moves: "Langkah",
      score: "Skor",
      won: "Luar Biasa! Anda Menang 🎉",
      play_again: "Main Lagi",
      back: "Kembali ke Hub",
      back_home: "Kembali ke Portfolio",
      play: "Mini Games",
      tictactoe_title: "Tic-Tac-Toe",
      tictactoe_desc: "Game strategi X dan O klasik.",
      turn: "Giliran",
      winner: "Pemenang",
      draw: "Seri!",
      fluppy_title: "Fluppy Wil",
      fluppy_desc: "Bantu Wildan terbang melewati rintangan!",
      start: "Mulai Game",
      gameover: "Game Over! 💥",
      love_title: "Love Animation",
      love_desc: "Visualisasi partikel teks berbentuk hati dinamis.",
      cryptarithm_title: "Cryptarithm",
      cryptarithm_desc: "Pecahkan teka-teki logika matematika terenkripsi!",
      sudoku_title: "Sudoku",
      sudoku_desc: "Teka-teki logika grid 9x9 klasik."
    }
  },
  en: {
    nav: {
      about: "About",
      projects: "Work",
      skills: "Skills",
      experience: "Experience",
      contact: "Contact",
      hire: "Get in Touch",
      available: "Available for Freelance",
    },
    hero: {
      eyebrow: "Front-End Developer · Bandung, ID",
      headline_1: "I BUILD DIGITAL",
      headline_2: "EXPERIENCES.",
      subheadline: "Front-End Developer with 3+ years of experience engineering high-performance web applications, scalable design systems, and resilient UI architectures using Next.js, React, Angular, and TypeScript.",
      view_work: "View Selected Work",
      lets_talk: "Let's Talk",
      experience_badge: "3+ Years Experience",
      role_badge: "Front-End Engineer",
      location_badge: "Bandung, Indonesia",
      status: "Available for Freelance & Projects",
    },
    about: {
      section_label: "01 / ABOUT ME",
      heading: "Bridging engineering rigor with intentional design craft.",
      bio_p1: "I am Wildan Jaelani, a Front-End Developer based in Bandung, Indonesia with 3+ years of experience. I specialize in building web interfaces that balance technical performance, accessible architecture, and meticulous visual precision.",
      bio_p2: "My everyday workflow centers around modern technologies including Next.js, React, Angular, TypeScript, and monorepo architectures. I enjoy solving complex front-end challenges and translating product ideas into delightful, resilient user experiences.",
      highlights: [
        { label: "Experience", value: "3+ Years" },
        { label: "Specialty", value: "Next.js · Angular · TS" },
        { label: "Location", value: "Bandung, ID" },
        { label: "Availability", value: "Open for Freelance" },
      ],
    },
    projects_section: {
      section_label: "02 / SELECTED WORK",
      heading: "Featured Case Studies",
      desc: "A curated selection of production work spanning enterprise-scale applications, monorepo architectures, and responsive web platforms.",
      view_demo: "View Live Demo",
      internal_project: "Internal Enterprise System",
      case_study: "Case Study",
      tech_stack: "Tech Stack",
    },
    skills_section: {
      section_label: "03 / CAPABILITIES",
      heading: "Technical Stack & Tools",
      desc: "Core technologies and workflows I leverage daily to engineer fast, maintainable, and scalable web interfaces.",
      all: "All",
    },
    experience_section: {
      section_label: "04 / CAREER TIMELINE",
      heading: "Professional Experience",
      desc: "A record of engineering contributions across enterprise platforms and production web applications.",
    },
    contact_section: {
      section_label: "05 / LET'S CONNECT",
      heading_1: "LET'S BUILD",
      heading_2: "SOMETHING GREAT.",
      desc: "Have an upcoming project, freelance opportunity, or want to discuss front-end architecture? Let's connect.",
      chat_whatsapp: "Chat on WhatsApp",
      send_email: "Send Email",
      view_linkedin: "Connect on LinkedIn",
      availability: "Currently accepting freelance projects",
      location_text: "Bandung, West Java, Indonesia (WIB / UTC+7)",
    },
    footer: {
      crafted: "Designed & Engineered by Wildan Jaelani",
      rights: "All Rights Reserved.",
      local_time: "Bandung Local Time (WIB)",
      back_to_top: "Back to Top",
    },
    profile: {
      name: "Wildan Jaelani",
      role: "Front-End Developer",
      bio: "Front-End Developer with 3+ years of experience. Specializing in Next.js, React, Angular, and TypeScript. Experienced in enterprise-grade platforms and freelance development.",
      email: "jwildan22904@gmail.com",
      whatsapp: "62895413466226",
      linkedin: "https://www.linkedin.com/in/wildan-j-82016b250/",
      location: "Bandung, West Java, Indonesia",
      photo: "/wildan2.png",
    },
    skills: [
      {
        category: "Frameworks",
        items: ["Next.js", "React", "Angular", "Angular Material", "Laravel"],
      },
      {
        category: "Languages",
        items: ["TypeScript", "JavaScript", "HTML5", "CSS3", "PHP"],
      },
      {
        category: "Styling & UI",
        items: ["Tailwind CSS", "Responsive UI", "Motion UI", "Bootstrap"],
      },
      {
        category: "Architecture & Tools",
        items: ["Hono (RPC)", "Monorepo", "REST API", "Git", "Axios", "Vercel"],
      },
    ],
    experiences: [
      {
        role: "Freelance Front-End Developer",
        company: "PT. Infinys System Indonesia",
        period: "May 2023 – Present",
        type: "Freelance / Contract",
        summary: "Leading UI engineering for enterprise event management systems with modern front-end architectures.",
        points: [
          "Architected and developed an enterprise event management application using Angular and Angular Material.",
          "Implemented a Monorepo architecture for enhanced code maintainability and cross-team modularity.",
          "Integrated type-safe backend APIs using Hono (RPC) with end-to-end predictability.",
          "Engineered high-performance UI components with TypeScript, Next.js, and Tailwind CSS.",
        ],
      },
      {
        role: "Front-End Developer Intern",
        company: "PT. Infinys System Indonesia",
        period: "Jan 2023 – Apr 2023",
        type: "Internship",
        summary: "Contributed to responsive UI slicing, REST API integrations, and web performance.",
        points: [
          "Translated complex UI/UX designs into pixel-perfect, responsive web layouts using Tailwind CSS.",
          "Integrated and consumed RESTful APIs in Next.js and React client applications.",
          "Maintained high accessibility standards, fast rendering speeds, and cross-browser consistency.",
        ],
      },
    ],
    projects: [
      {
        id: "01",
        title: "Event Management Application",
        category: "Enterprise System",
        subtitle: "Enterprise Application & Monorepo Architecture",
        desc: "An enterprise-grade event management platform designed to orchestrate complex registration workflows, attendee schedules, and event operations in real time. Built with Angular and Angular Material inside a Monorepo architecture with Hono RPC integration for high stability.",
        tags: ["Angular", "TypeScript", "Hono RPC", "Monorepo", "Angular Material"],
        link: "",
        image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&q=85",
        year: "2023 – 2024",
        highlight: "Enterprise Scale",
      },
      {
        id: "02",
        title: "Nusantara Coffee",
        category: "Brand & Web Platform",
        subtitle: "Cafe Landing Page & Interactive Menu",
        desc: "A warm and responsive digital presence for a specialty coffee brand. Features dynamic category menu filtering, instant WhatsApp order direct-link generation, and high-performance static delivery on Next.js and Tailwind CSS.",
        tags: ["Next.js", "TypeScript", "Tailwind CSS", "Vercel"],
        link: "https://cafe-landing-sage.vercel.app/",
        image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=1200&q=85",
        year: "2024",
        highlight: "Live Platform",
      },
      {
        id: "03",
        title: "Golden Stall (Warung Emas)",
        category: "Hospitality & Dining",
        subtitle: "Fine Dining Restaurant Showcase",
        desc: "A premium restaurant landing page with elegant visual presentation. Showcases curated food photography, responsive menu categories, silky micro-interactions, and fast load times with Next.js and Tailwind CSS.",
        tags: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion"],
        link: "https://warung-emas.vercel.app",
        image: "https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=1200&q=85",
        year: "2024",
        highlight: "Live Platform",
      },
    ],
    game: {
      hub_title: "Game Hub",
      hub_desc: "A collection of interactive mini-games built with pure Front-End logic.",
      play_now: "Play Game",
      title: "Tech Memory Match",
      desc: "Find matching technology pairs under the cards!",
      moves: "Moves",
      score: "Score",
      won: "Awesome! You Won 🎉",
      play_again: "Play Again",
      back: "Back to Hub",
      back_home: "Back to Portfolio",
      play: "Mini Games",
      tictactoe_title: "Tic-Tac-Toe",
      tictactoe_desc: "Classic X and O strategy game.",
      turn: "Turn",
      winner: "Winner",
      draw: "It's a Draw!",
      fluppy_title: "Fluppy Wil",
      fluppy_desc: "Help Wildan fly through obstacles!",
      start: "Start Game",
      gameover: "Game Over! 💥",
      love_title: "Love Animation",
      love_desc: "Dynamic heart-shaped particle typography.",
      cryptarithm_title: "Cryptarithm",
      cryptarithm_desc: "Solve encrypted mathematical logic puzzles!",
      sudoku_title: "Sudoku",
      sudoku_desc: "Classic 9x9 logic grid challenge."
    }
  }
}
